[package]
name = "epochs-cli"
version = "0.1.0"
authors = ["Tim Heaney <oylenshpeegul@pm.me>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
epochs = "0.2"
itertools = "0.8"
lazy_static = "1.4"
maplit = "1.0"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
structopt-derive = "0.4"
